import { TechniqueConfig } from '@/types';

export const TECHNIQUES: Record<string, TechniqueConfig> = {
  'zero-shot': {
    id: 'zero-shot',
    title: 'Zero-Shot Prompting',
    description: 'Ask the AI directly without any examples. The model relies entirely on its pre-trained knowledge. This is the simplest approach — just describe what you want clearly.',
    tip: '💡 Tip: Be specific and clear. "Classify this as positive or negative" works better than "What do you think?"',
    systemPrompt: 'You are a helpful assistant.',
    userPrompt: 'Classify the following movie review as positive, negative, or neutral:\n\n"The cinematography was breathtaking but the plot felt rushed and predictable."',
    showSections: ['systemPromptSection', 'paramsSection'],
  },
  'few-shot': {
    id: 'few-shot',
    title: 'Few-Shot Prompting',
    description: 'Provide examples before your actual question so the AI learns the pattern. This dramatically improves accuracy for specific tasks — the AI mimics the format and logic of your examples.',
    tip: '💡 Tip: Use 2-5 diverse examples. Quality matters more than quantity.',
    systemPrompt: 'You are a sentiment classifier. Follow the pattern shown in the examples exactly.',
    userPrompt: 'Review: "The special effects were amazing but I fell asleep during the second act."\nSentiment:',
    examples: [
      { input: 'Review: "Absolutely loved every minute! A masterpiece."\nSentiment:', output: 'Positive (confidence: 95%)' },
      { input: 'Review: "Terrible acting and a boring script. Waste of money."\nSentiment:', output: 'Negative (confidence: 92%)' },
      { input: 'Review: "It was okay, nothing special but not bad either."\nSentiment:', output: 'Neutral (confidence: 78%)' },
    ],
    showSections: ['systemPromptSection', 'fewShotSection', 'paramsSection'],
  },
  'chain-of-thought': {
    id: 'chain-of-thought',
    title: 'Chain-of-Thought (CoT)',
    description: 'Add "Let\'s think step by step" or similar reasoning triggers. This forces the AI to show its reasoning process, which dramatically improves accuracy on complex logic, math, and multi-step problems.',
    tip: '💡 Tip: CoT shines on math, logic puzzles, and multi-step reasoning. Less useful for creative tasks.',
    systemPrompt: 'You are a logical reasoning assistant. Always show your complete reasoning step by step before giving the final answer.',
    userPrompt: 'A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?',
    cotInstruction: "Let's think through this step by step:\n1. Define variables for what we know\n2. Set up the equation\n3. Solve carefully\n4. Verify the answer",
    showSections: ['systemPromptSection', 'cotSection', 'paramsSection'],
  },
  'role-prompting': {
    id: 'role-prompting',
    title: 'Role Prompting',
    description: 'Assign the AI a specific expert persona. By saying "You are a senior Python developer" or "You are a tax accountant with 20 years of experience," the AI adjusts its vocabulary, depth, and perspective.',
    tip: '💡 Tip: The more specific the role, the better. Include years of experience, specialization, and communication style.',
    systemPrompt: '',
    userPrompt: 'How should I structure a large Python project with multiple teams contributing?',
    roles: [
      { label: '👨‍💻 Senior Developer', prompt: 'You are a senior software engineer with 15 years of experience in Python, specializing in clean architecture and scalable system design. You give practical, opinionated advice with code examples.' },
      { label: '📊 Data Scientist', prompt: 'You are a lead data scientist at a FAANG company with expertise in ML pipelines, experiment tracking, and data engineering. You focus on reproducibility and best practices.' },
      { label: '🔒 Security Expert', prompt: 'You are a cybersecurity consultant with CISSP certification and 10 years of experience. You always consider security implications, threat models, and OWASP guidelines.' },
      { label: '👶 ELI5 Teacher', prompt: 'You are a patient teacher who explains complex topics to complete beginners. Use simple analogies, avoid jargon, and break everything into tiny digestible steps.' },
      { label: '📝 Tech Writer', prompt: 'You are a technical documentation specialist. You prioritize clarity, structure, and completeness. Use proper formatting with headers, lists, and examples.' },
    ],
    showSections: ['systemPromptSection', 'roleSection', 'paramsSection'],
  },
  'output-format': {
    id: 'output-format',
    title: 'Output Formatting',
    description: 'Constrain the AI\'s response to a specific format — JSON, Markdown table, bullet points, XML, etc. This is essential when building apps that need to parse AI responses programmatically.',
    tip: '💡 Tip: Provide an example of the exact output shape you expect. The AI follows structure better than instructions.',
    systemPrompt: 'You are a helpful assistant that always responds in the exact format requested. Never deviate from the specified output format.',
    userPrompt: 'Analyze the programming language Python. Include its strengths, weaknesses, common use cases, and a difficulty rating.',
    formats: [
      { label: '📦 JSON', instruction: 'Respond ONLY with valid JSON in this exact format:\n{\n  "name": "...",\n  "strengths": ["...", "..."],\n  "weaknesses": ["...", "..."],\n  "use_cases": ["...", "..."],\n  "difficulty": "beginner|intermediate|advanced",\n  "rating": 1-10\n}' },
      { label: '📊 Table', instruction: 'Respond with a well-formatted Markdown table with these columns: Aspect, Details, Rating (1-5 stars).' },
      { label: '📋 Bullet Points', instruction: 'Respond with structured bullet points using this format:\n• **Category**: Description\n  - Sub-detail 1\n  - Sub-detail 2' },
      { label: '📝 Report', instruction: 'Respond with a structured report using:\n# Title\n## Section headers\n- Key findings\n> Important quotes or highlights\n**Bold** for emphasis' },
    ],
    showSections: ['systemPromptSection', 'formatSection', 'paramsSection'],
  },
  'temperature': {
    id: 'temperature',
    title: 'Temperature Comparison',
    description: 'Temperature controls randomness in AI responses. At 0.0 the AI picks the most likely answer (deterministic). At 1.0 it\'s more creative and varied. Compare the same prompt at 3 different temperatures side-by-side.',
    tip: '💡 Tip: Use low temp (0-0.3) for factual/code tasks. Use high temp (0.7-1.0) for creative writing.',
    systemPrompt: 'You are a creative assistant.',
    userPrompt: 'Write a one-paragraph product description for a smart water bottle that tracks hydration.',
    showSections: ['systemPromptSection'],
  },
};
